services:
  migrate:
    image: ghcr.io/ostefanini/drawn-lights-demo-os/prisma-migrate:latest
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  web-react:
    image: ghcr.io/ostefanini/drawn-lights-demo-os/web-react:latest
    container_name: "web-react"
    group_add:
      - "120"
    volumes:
      - /etc/letsencrypt/live/:/certs/live:ro
      - /etc/letsencrypt/archive:/certs/archive:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    networks:
      public:
        aliases:
          - demo-os-web-react
    depends_on:
      api-nestjs:
        condition: service_started

  api-nestjs:
    image: ghcr.io/ostefanini/drawn-lights-demo-os/api-nestjs:latest
    container_name: "api-nestjs"
    ports:
      - 127.0.0.1:4000:4000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  postgres:
    image: postgres:16
    container_name: prod_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: prod_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  public:
    external: true