name: demo-os-prod-local

services:
  migrate:
    build:
      context: .
      dockerfile: packages/prisma/Dockerfile
    env_file:
      - .env.prod.local
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build: 
      context: .
      dockerfile: apps/web-react/Dockerfile
    # dockerfile: apps/web-nextjs/Dockerfile
    container_name: "local_prod_web"
    volumes:
      - ./certs:/certs:ro
      - ./nginx.prod.local.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      api:
        condition: service_started

  api:
    build: 
      context: .
      #dockerfile: apps/api-expressjs/Dockerfile
      dockerfile: apps/api-nestjs/Dockerfile
    container_name: "local_prod_api"
    env_file:
      - .env.prod.local
    ports:
      - 127.0.0.1:4000:4000
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  postgres:
    image: postgres:16
    container_name: local_prod_postgres  
    env_file:
      - .env.prod.local
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app.local.prod}
      POSTGRES_USER: ${POSTGRES_USER:-app.local.prod}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app.local.prod}
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app.local.prod -d app.local.prod"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: local_prod_pgadmin
    env_file:
      - .env.prod.local
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.prod}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin.local.prod}
    ports:
      - "5051:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - prod_pgadmin_data:/var/lib/pgadmin

volumes:
  prod_postgres_data:
  prod_pgadmin_data:

